### ISSUE TITLE
ITERATION 3: Program Page Mock-up [UI]

### ISSUE THREAD

**Issue by ShajibGit** [ShajibGit/SoftwareEngineering#8]

**Comment by percianjosephborja** [comment]
Anything I need to check?

Please include here as attachment.

**Comment by percianjosephborja** [comment]
@EusebioHerlyn

**Comment by EusebioHerlyn** [comment]
Yung news and events po sir, naka upload na po sa github.
Ayusin lang po namin.

Thankyouu po

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by EusebioHerlyn** [comment]
Good evening po sir. hindi po maka pag attach ng file hanggang 25mb lang po ang kaya.

**Comment by EusebioHerlyn** [comment]
https://drive.google.com/file/d/1Z5rv7Ohs_RouXXIMnVkbOOo2M94rl0c1/view?usp=sharing

**Comment by Jaecee1802** [comment]
Sir goid afternoon po @percianjosephborja ano ano pa po ang pwede po iadd dun sa mga front end po sir any suggestions po? Syaka po yung ibang pages po naupload na po dito
